default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_property_manager_development

test:
  <<: *default
  database: my_property_manager_test

production:
  <<: *default
  database: my_property_manager_production
